version: '3.4'

services:
  webapi:
    image: fsbr_agendasalas_api
    build:
      context: .
      dockerfile: FSBR_AgendaSalas.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AgendaSalas;User=sa;Password=Password@1234

  mvc:
    image: fsbr_agendasalas_mvc
    build:
      context: .
      dockerfile: FSBR_AgendaSalas.MVC/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - webapi

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Password@1234
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - default
